### PR TITLE
Varying time tests for logger

### PR DESCRIPTION
**Pull request by mifrandir**

### CODE REVIEW

**Comment by mifrandir** [comment]
Actually, when we are at time 0, why do we print `01:00:00.000`, @kshxtij?

**Review by kshxtij — APPROVED** [review]

**Comment by kshxtij** [comment]
localtime vs gmtime semantics

**Review by TomLonergan03 — APPROVED** [review]

**Comment by mifrandir** [comment]
> localtime vs gmtime semantics

but we don't want our tests to depend on the timezone, do we?

**Comment by kshxtij** [comment]
I see what you mean, but we'd want our logs to display timestamps based on the local timezone

**Comment by mifrandir** [comment]
> I see what you mean, but we'd want our logs to display timestamps based on the local timezone

So I've tried to fix this put `std::chrono::parse` seems to not exist yet so this is a future problem. A solution would be to figure out what "00:00:00.000" on 1970-01-01 gets parsed to in local time and then add an offset to that. Not to big an issue, though.

**Comment by mifrandir** [comment]
@kshxtij merge whenever you want

**Pull request merged**
