### PR TITLE
Link against Boost

### PR DESCRIPTION
**Pull request by kshxtij**

### CODE REVIEW

**Review by mifrandir — CHANGES_REQUESTED** [review]
can you please add a test to convince me that boost works?

maybe for eigen, too

**Comment by kshxtij** [comment]
Sure, will do that just within test/core

**Review by mifrandir — APPROVED** [review]

**Review by SnickeyX — APPROVED** [review]
Code is fine, could you add eigen + boost as an explicit dependency that needs to be downloaded to the readme or wiki

**Review by TomLonergan03 — APPROVED** [review]
builds

**Review by maxguy2001 — APPROVED** [review]

**Pull request merged**
